### ISSUE TITLE
Failed to initialize keyboard hotkeys through kernel.

### ISSUE THREAD

**Issue by huafengtc** [Enoouo/Pro-CS2_DMA#11]
Failed to initialize keyboard hotkeys through kernel. How to fix this problem?

**Comment by huafengtc** [comment]
![Uploading 屏幕截图 2024-08-29 211801.png…]()

**Comment by huafengtc** [comment]
![屏幕截图 2024-08-29 211801](https://github.com/user-attachments/assets/e9466d99-06af-4f03-a9f2-7e34fd47cff3)

**Comment by Enoouo** [comment]
Is your system version greater than 22631.3737 ?

**Comment by huafengtc** [comment]
Yes,Windows 11,版本	Windows 11 专业版
版本号	23H2
安装日期	‎2024/‎6/‎16
操作系统版本	22631.4112
体验	Windows Feature Experience Pack 1000.22700.1034.0

**Comment by huafengtc** [comment]
115/10000
实时翻译
115/10000实时翻译版本Windows 11专业版版本号23H2安装日期2024/6/16操作系统版本22631.4112体验Windows功能体验包1000.2270.1034.0

划译
Version Windows 11 Professional
Version number 23H2
Installation date 2024/6/16
Operating system version 22631.4112
Experience Windows Feature Experience Pack 1000.2270.1034.0

**Comment by huafengtc** [comment]
Version Windows 11 Professional
Version number 23H2
Installation date 2024/6/16
Operating system version 22631.4112
Experience Windows Feature Experience Pack 1000.2270.1034.0

**Comment by huafengtc** [comment]
Can system issues be fixed？

**Comment by Enoouo** [comment]
Fixed. Please download again.

**Comment by Thirteenlz** [comment]
请问这个问题你有解决了吗 如果解决了的话放不方便告知方法
