### ISSUE TITLE
Share project

### ISSUE THREAD

**Issue by akumareutre** [Enoouo/Pro-CS2_DMA#14]
Hello, I wanted to know if you could share the source project because I think that this project can be by far the most successful cs2 dma project or would you prefer to keep it for yourself which I will completely understand Thank you for your response

**Comment by Enoouo** [comment]
The code contains a lot of comments and deprecated sections. The source code will only be released once it is fully refined.

**Comment by Snip1-99** [comment]
We look forward to hearing from you
