### ISSUE TITLE
Stuttering

### ISSUE THREAD

**Issue by wokonly** [Enoouo/Pro-CS2_DMA#15]
Whenever I have it running and I'm in game it will stutter or lag and I'm not really sure why as a hardware issue or software issue

**Comment by Enoouo** [comment]
I need more information, such as your FPS and the computer configuration you're running the program on. Maybe you could record a video.

As far as I know, some user run it on 2015 laptops without this issue, and the frame rate is around 120 FPS.

**Comment by wokonly** [comment]
> I need more information, such as your FPS and the computer configuration you're running the program on. Maybe you could record a video.
> 
> As far as I know, some user run it on 2015 laptops without this issue, and the frame rate is around 120 FPS.

i do get good fps just random freezing and stuttering and i dont seem to get these issues with any other cheats

PC:
CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
GPU: NVIDIA GeForce RTX 3060

Laptop:
CPU: 12th Gen Intel(R) Core(TM) i5-12500H
GPU: NVIDIA GeForce RTX 3060 Laptop GPU

Video:
https://github.com/user-attachments/assets/820bed64-b354-4187-8361-b29596237f53

**Comment by Enoouo** [comment]
It might be related to your DMA reading speed. What is your reading speed or DMATest speed?
Also, check if the `PCIE_CAP_ON` option is enabled in your firmware.

**Comment by wokonly** [comment]
> It might be related to your DMA reading speed. What is your reading speed or DMATest speed? Also, check if the `PCIE_CAP_ON` option is enabled in your firmware.

yes its enabled

**Comment by Enoouo** [comment]
So what about the speed? For example, the speed tested using the DMATest tool?

**Comment by wokonly** [comment]
> So what about the speed? For example, the speed tested using the DMATest tool?
![image](https://github.com/user-attachments/assets/d4ddedce-708c-4594-8475-cb5e3d586946)
this is my test using lonedma test or whatever its called and im not sure if its firmware or the device since i have a leetdma card

**Comment by Enoouo** [comment]
12.41MB/s? That's too slow. Check if you're using USB 2; the 35T DMA speed usually reaches around 180MB/s.

**Comment by wokonly** [comment]
> 12.41MB/s? That's too slow. Check if you're using USB 2; the 35T DMA speed usually reaches around 180MB/s.

Okay so I brought a new usb c cable that is using usb c to usb c and it arives oct 9th i think so once that arrives ill test it and if i get the same issue it could be my firmware

**Comment by wokonly** [comment]
firmware issue
