### ISSUE TITLE
Inquiry About Open Source Release

### ISSUE THREAD

**Issue by LuokeX** [Enoouo/Pro-CS2_DMA#17]
Hi Enoouo

First of all, thank you for your amazing work on this project! I wanted to ask if you have any plans to open-source the code, and if so, when do you expect to release it?

I understand that maintaining and preparing a project for open sourcing can take time, so I’d appreciate any information you can provide regarding the roadmap or an estimated timeline.

Thanks again for your efforts, and I look forward to your response!

Best regards,  
Luoke

**Comment by Enoouo** [comment]
Sorry, there are still some features that I have not implemented. I will release the source code after completing them.
