### ISSUE TITLE
Only the ESP is visible

### ISSUE THREAD

**Issue by Dekos-lgbty** [Enoouo/Pro-CS2_DMA#21]
Hi. Today I decided to try this software and faced the problem that I have only ESP working, nothing opens on F8 button.

**Comment by Enoouo** [comment]
F8 ? What does it mean?

**Comment by Dekos-lgbty** [comment]
> F8 ? What does it mean?

isnt that the button that opens the cheat menu? O.o

**Comment by Enoouo** [comment]
There is no GUI menu, all settings are in config.cfg, and changes can be modified in real-time while running.
