### ISSUE TITLE
The memwrite aimbot does not working

### ISSUE THREAD

**Issue by Geitost** [Enoouo/Pro-CS2_DMA#22]
When I use the memwrite aimbot the cursor on my second pc moves, not the one on my main computer. Just want to say this when I have the chance, this software is great. Thank you for sharing for free 😄

**Comment by Enoouo** [comment]
//non-Kmbox users and 2PC, use "write"   	Ps: Note that this method involves writing to memory, which I haven't tried before; it's a feature requested by a user.

kmboxType=write
