### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by HH333** [Enoouo/Pro-CS2_DMA#23]
Hello, it is not recommended to add the memory writing function.
The game will be banned if the memory is written

**Comment by Enoouo** [comment]
Memory writes only occur when `kmboxType=write`, based on requests from some users.

**Comment by HH333** [comment]
Found in the test  ，magnet_triggerbot   Not as fast or accurate as the previous version

**Comment by HH333** [comment]
Web Radar Very good

**Comment by HH333** [comment]
Thank you very much, thank you for your hard work
