### ISSUE TITLE
magnet_triggerbot 

### ISSUE THREAD

**Issue by HH333** [Enoouo/Pro-CS2_DMA#24]
Found in the test ，magnet_triggerbot Not as fast or accurate as the previous version

**Comment by Enoouo** [comment]
The value of `magnet_triggerbot_smooth` was previously fixed at 0, but now it can be modified. If it's not fast enough, you can try lowering the value or directly setting it to 0.

**Comment by Enoouo** [comment]
Regarding accuracy, I believe that in high-level matches, having too much accuracy with pistols isn't necessarily a good thing. I've used the modified `magnet_triggerbot` for a while and think it's acceptable. If I receive more feedback or discover any issues, I will make further improvements.

**Comment by HH333** [comment]
Thank you very much, thank you for your hard work

**Comment by HH333** [comment]
> Regarding accuracy, I believe that in high-level matches, having too much accuracy with pistols isn't necessarily a good thing. I've used the modified `magnet_triggerbot` for a while and think it's acceptable. If I receive more feedback or discover any issues, I will make further improvements.

After two days of extensive testing
The network radar is no longer stuck/delayed, but there is a serious problem. The radar will not be displayed for computer players who are offline or logged out. This did not happen in the previous version.


About   magnet_triggerbot  .Let me correct my expression yesterday.     magnet_triggerbot  The problem with the new version is the delay in shooting. After aiming is locked, there is a delay in shooting.   

Version 1.2, magnet_triggerbot has no delay when firing and reacts very quickly.

**Comment by Enoouo** [comment]
The radar issue will be fixed later, I've been a bit busy these days. I’ll do more testing on the `magnet_triggerbot` afterwards.

**Comment by Enoouo** [comment]
A simpler way would be to put the delay shoot time setting into the config, allowing users to customize it, which should solve your problem.

**Comment by HH333** [comment]
> A simpler way would be to put the delay shoot time setting into the config, allowing users to customize it, which should solve your problem.

Thank you very much, thank you for your hard work

**Comment by Enoouo** [comment]
The radar issue has been fixed and will be released in the next version. For now, if you encounter this problem, try refreshing the webpage.
