### ISSUE TITLE
failed to get key state

### ISSUE THREAD

**Issue by 1231adsada** [Enoouo/Pro-CS2_DMA#27]
failed to initialize keyboard keys

**Comment by CKJ7921** [comment]
我也遇到这个问题了，前天打还没事，难道CS2又更了？

**Comment by CKJ7921** [comment]
还有个问题就是win11打不开雷达，一点打开就报无法运行错误

**Comment by Enoouo** [comment]
What is the system version number?

**Comment by Enoouo** [comment]
> 还有个问题就是win11打不开雷达，一点打开就报无法运行错误

跟win11无关，给出具体报错提示

**Comment by CKJ7921** [comment]
没事了，可能是我操作问题

**Comment by Enoouo** [comment]
> failed to initialize keyboard keys

Has the problem been resolved? I noticed you have no follow-up reply. If it has been resolved, I will close this issue.
