### ISSUE TITLE
Kmbox b

### ISSUE THREAD

**Issue by ItsMeBeast** [Enoouo/Pro-CS2_DMA#29]
Cheat crashes if i try to use kmbox b

**Comment by Enoouo** [comment]
As far as I know, B+ users can use it. Does the program crash immediately upon startup, or is there any console message? Did it indicate a successful connection? I need more information to help identify potential issues.

**Comment by ItsMeBeast** [comment]
When I sent config to kmboxb it opens says its looking for kmbox then closes

**Comment by ItsMeBeast** [comment]
any known fix?
or a way i can send u a clip?

**Comment by Enoouo** [comment]
Sure, record a video and check if you've customized the baud rate.

**Comment by ItsMeBeast** [comment]
could it be because i use arduino?

**Comment by Enoouo** [comment]
Arduino? Maybe that's the reason.
