### ISSUE TITLE
扳机问题

### ISSUE THREAD

**Issue by WWW88944** [Enoouo/Pro-CS2_DMA#30]
我是net用户，不开磁性扳机只开起扳机也是磁性扳机效果，而且会敌方还有两三个身位扳机就会开枪。

**Comment by WWW88944** [comment]
大佬有没有dc或者飞机交流群

**Comment by BaileyZyp** [comment]
你是不是按键绑定成同一个了

**Comment by Enoouo** [comment]
确实，你是不是两个绑到同一个按键了？另外扳机在延迟时间后即使没目标也会自动开枪，按住的的话不会延迟开枪，会直有目标或者松开按键的时候才会开枪

**Comment by Enoouo** [comment]
如果你觉得还有问题，请录段视频并附上相关的config设置

**Comment by Enoouo** [comment]
如果有问题请重新打开这个 issue
