### ISSUE TITLE
大佬能否添加快捷键切换头身，一直锁头太假了

### ISSUE THREAD

**Issue by CKJ7921** [Enoouo/Pro-CS2_DMA#34]

**Comment by Enoouo** [comment]
晚点会添加aimbot自定义部位。
不过即使是现在的并不假，当你射击的时候会去压枪，这会干扰自瞄产生随机性，并不存在一直锁头，或许是你参数或者使用方式的问题。
我在每个平台都是顶分段，之前demo也被知名主播看过，并没有任何问题。
