### ISSUE TITLE
Web Radar

### ISSUE THREAD

**Issue by 857868581** [Enoouo/Pro-CS2_DMA#36]
I changed the Web Radar IP in the config file and replaced it with my cloud server IP. The Web Radar is running on my cloud server, and the web access IP：7788. However, when I enter the game, the web page displays "Error reading the map file." How can I solve this problem?

**Comment by Enoouo** [comment]
// Serves static files, such as HTML. Use this one in your browser
"static": 7788,
// Dynamic websocket port, used for live data transport
"socket": 3344

You need to open both ports. If you only open port 7788, you can access the webpage, but you won't be able to receive data.
