### ISSUE TITLE
新版本似乎有bug

### ISSUE THREAD

**Issue by BaileyZyp** [Enoouo/Pro-CS2_DMA#37]
![image](https://github.com/user-attachments/assets/5f8d8241-321c-4725-b32d-286bc8addad6)
启动后就一直在这个界面没有下一步，雷达也没有数据

**Comment by Enoouo** [comment]
咦，你只用雷达吗？

**Comment by Enoouo** [comment]
你有discord吗？

**Comment by Enoouo** [comment]
你发我加你

**Comment by BaileyZyp** [comment]
> 你发我加你

https://discord.gg/fKDHEN2x
