### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by eden13378** [Enoouo/Pro-CS2_DMA#4]
Please add transparent and layered mode to overlay.
I use second monitor but it's fully black and it's  cover radar tab in browser.

**Comment by Enoouo** [comment]
Got it, I'll address this issue in the next update. For now, you can use your phone to view the radar.

**Comment by Enoouo** [comment]
I added a non-topmost mode and transparency, but there are some minor issues with the transparency that I haven't figured out how to solve yet. However, it should still be usable. For specific details, you can check the release notes where I mentioned the problem.

**Comment by Enoouo** [comment]
> overlay and transparency work, but if the overlay is on top it is impossible to control game.

Do you need a property to allow mouse events to pass through the window?

> And it is also possible that your cfg does not work correctly because of extra lines and extra text in the cfg, which probably should not be there, and the cfg is incorrectly read and yes, after deleting the file, a new one is not created. (Srry for Google translate)

It seems that Chinese notesare causing issues with reading the config file. Removing them should resolve the problem. I just checked the code and confirmed that a new config file will not be generated. I accidentally commented out that part of the code, will fix later

**Comment by Enoouo** [comment]
Please re-download the newly released version.

**Comment by Enoouo** [comment]
Did the aimbot work correctly in the previous version?

**Comment by Enoouo** [comment]
[Pro CS2.zip](https://github.com/user-attachments/files/16820314/Pro.CS2.zip)

I just tested it and realized I missed a parameter. It should work now—give this a try.

**Comment by Enoouo** [comment]
discord: aboutlife
add me

**Comment by y287869864** [comment]
Windows系统有个比较恶心的机制 就是你的窗口达到系统最大分辨率时，会进行全屏幕优化。导致透明，绘制等效果不如人意
你可以获取分辨率时将X和Y分别减1 让他达到非全屏效果
然后使用Windows函数 达到透明渲染层的效果
`SetWindowLong(hwnd, GWL_EXSTYLE, GetWindowLong(hwnd, GWL_EXSTYLE) | WS_EX_LAYERED);
SetLayeredWindowAttributes(hwnd, 0, 0, 1); // 第三个参数为透明度，255表示完全不透明`

**Comment by Enoouo** [comment]
> Windows系统有个比较恶心的机制 就是你的窗口达到系统最大分辨率时，会进行全屏幕优化。导致透明，绘制等效果不如人意 你可以获取分辨率时将X和Y分别减1 让他达到非全屏效果 然后使用Windows函数 达到透明渲染层的效果 `SetWindowLong(hwnd, GWL_EXSTYLE, GetWindowLong(hwnd, GWL_EXSTYLE) | WS_EX_LAYERED); SetLayeredWindowAttributes(hwnd, 0, 0, 1); // 第三个参数为透明度，255表示完全不透明`

晚点我试试，这个还好，有个问题想不通，有的人用esp会有滞后效果，有的人又没有

**Comment by y287869864** [comment]
这种有很多原因
1.主辅机刷新率问题
2.DMA读取速率问题（插USB2.0 跑个两三千的用户比比皆是）
3.硬件低导致软件FPS太低
4.软件环境
5.CPU太老（志强） 指令集缺失
就算是做比较简单的外部作弊 都有很多兼容性问题 更别说变量更多的DMA作弊 

> > Windows系统有个比较恶心的机制 就是你的窗口达到系统最大分辨率时，会进行全屏幕优化。导致透明，绘制等效果不如人意 你可以获取分辨率时将X和Y分别减1 让他达到非全屏效果 然后使用Windows函数 达到透明渲染层的效果`SetWindowLong(hwnd, GWL_EXSTYLE, GetWindowLong(hwnd, GWL_EXSTYLE) | WS_EX_LAYERED); SetLayeredWindowAttributes(hwnd, 0, 0, 1); // 第三个参数为透明度，255表示完全不透明`
> 
> 晚点我试试，这个还好，有个问题想不通，有的人用esp会有滞后效果，有的人又没有

**Comment by Enoouo** [comment]
about aimbot, try the new version.

**Comment by Enoouo** [comment]
Fixed the overlay transparency issue, it can now be fully transparent.
