### ISSUE TITLE
大佬，发现一个普通自动扳机问题

### ISSUE THREAD

**Issue by CKJ7921** [Enoouo/Pro-CS2_DMA#41]
为什么有时候出现人了也不开枪，我打人机试了好几把了都是这样，还有就是扳机键需要和自瞄键放一块吗

**Comment by CKJ7921** [comment]
还遇到一个雷达打开后，我CFG里面修改了7788，然后cmd那个窗口出现ERROR: Got bad status connecting to ws://127.0.0.1:7788: HTTP/1.1 200 OK
并且网站打开后鼠标处于无法选择的状态

**Comment by Enoouo** [comment]
> 为什么有时候出现人了也不开枪，我打人机试了好几把了都是这样，还有就是扳机键需要和自瞄键放一块吗

无论是自瞄、扳机、磁性扳机，都需要设置单独的按键。
不开枪的问题我没遇到，现在只能对敌对队伍生效。
还有就是今天游戏更新了，你重新下载程序了吗？

**Comment by CKJ7921** [comment]
> > 还遇到一个雷达打开后，我CFG里面修改了7788，然后cmd那个窗口出现ERROR: Got bad status connecting to ws://127.0.0.1:7788: HTTP/1.1 200 OK 并且网站打开后鼠标处于无法选择的状态
> 
> //提供静态HTML “static”： 7788， // 动态 websocket 端口，用于实时数据传输 “socket”： 3344
> 
> 你需要理解这是什么意思
刚才问了问GPT，感觉太难了，不是一个方向的，有没有最简单的办法？

**Comment by CKJ7921** [comment]
3344那个端口应该启动了，现在cmd那个窗口报 request error: Couldn't resolve host name

**Comment by Enoouo** [comment]
默认的不能用吗？为什么要改?

**Comment by Enoouo** [comment]
长时间没回复默认你已经解决了，如果有问题请重新打开这个issues
