### ISSUE TITLE
About Network Radar Internal Network Penetration

### ISSUE THREAD

**Issue by kisadfnlnv** [Enoouo/Pro-CS2_DMA#42]
Hello, respected author. I tried to map the 7788 port of the local radar through internal network penetration. The radar can be viewed in the website of the internal network, but after penetrating through the internal network, the mapped website appears blank. Did I not set it correctly? Or does the current software not support internal network penetration mapping radar?

**Comment by Enoouo** [comment]
https://github.com/Enoouo/Pro-CS2_DMA/issues/36

**Comment by kisadfnlnv** [comment]
My intranet penetration cannot set up a remote port to map two local ports 7788 and 3344. Is there any other solution?

**Comment by kisadfnlnv** [comment]
My internal network can only penetrate one remote port and correspond to one local port. I cannot make one remote domain name correspond to two local ports 7788 and 3344 at the same time. What should I do? Dear author

**Comment by Enoouo** [comment]
The domain name doesn't need to correspond to both ports. Port 7788 serves the HTML access, while port 3344 is for data transmission within the HTML. After opening these two ports, you can simply access `example.com:7788` or the `IP:7788`.

If it's for internal network access, no extra setup is needed. What exactly are you looking for? Are you trying to let your friends access your radar?

**Comment by Enoouo** [comment]
Perhaps you can use Radmin VPN, a free tool. Once others connect, they will be on the same local network as you.

**Comment by 857868581** [comment]
我在服务器上打开了两个端口，软件连接后打开网页显示找不到地图文件，这个问题到现在我依旧没有找到解决办法

**Comment by Enoouo** [comment]
> 我在服务器上打开了两个端口，软件连接后打开网页显示找不到地图文件，这个问题到现在我依旧没有找到解决办法

telnet 一下你的端口是否能访问

**Comment by kisadfnlnv** [comment]
Yes, I want my friends to see my radar. I followed your instructions and ensured that both ports were open, but the remote port still couldn't see the real-time image of the radar. I tried using other tools to let my friends see the radar, but the effect was not ideal, with delays and lagging.
The other single radar function software I used before, this one https://github.com/Mzzzj/CS2_DMA_Radar。 I only need to map one port 8080 so that my friends can see my radar image. However, the one I used before did not have platform decryption function, so I would like to request the author to create a radar software similar to this one that can remotely view radar images and decrypt platforms by mapping only one port

**Comment by kisadfnlnv** [comment]
Yes, I want my friends to see my radar. I followed your instructions and ensured that both ports were open, but the remote port still couldn't see the real-time image of the radar. I tried using other tools to let my friends see the radar, but the effect was not ideal, with delays and lagging.
The other single radar function software I used before, this one https://github.com/Mzzzj/CS2_DMA_Radar I only need to map one port 8080 so that my friends can see my radar image. However, the one I used before did not have platform decryption function, so I would like to request the author to create a radar software similar to this one that can remotely view radar images and decrypt platforms by mapping only one port

**Comment by Enoouo** [comment]
Use telnet to test if the port is accessible

**Comment by Enoouo** [comment]
An encrypted platform? 5E?

**Comment by 857868581** [comment]
抱歉，我并没有成功开启副机3344端口，现在已经成功了，感谢，我还有一些问题，手机端访问网页雷达界面不居中，双方队伍颜色和自己颜色区别不太大容易弄混，双方换队伍之后地图不会更换方向，用户能修改雷达地图图片（想在图片上加上文本位置），希望后续改进，再次感谢作者！
![WVBR%O3J8~XR_9M)J _I`2U](https://github.com/user-attachments/assets/ecf329ac-3ff4-418f-8231-b7b91ea2392a)

**Comment by 857868581** [comment]
Sorry, I was unable to successfully open port 3344 on the secondary machine. It has now been successful. Thank you. I still have some issues. The radar interface on the mobile phone is not centered when accessing the webpage, and the colors of both teams are not very different from my own color, which makes it easy to confuse. After changing teams, the map will not change direction. Users can modify the radar map image (if they want to add text positions to the image). I hope to improve it in the future. Thank you again, author！
![Uploading WVBR%O3J8~XR_9M)J[_I`2U.png…]()

**Comment by 857868581** [comment]
Sorry, I was unable to successfully open port 3344 on the secondary machine. It has now been successful. Thank you. I still have some issues. The radar interface on the mobile phone is not centered when accessing the webpage, and the colors of both teams are not very different from my own color, which makes it easy to confuse. After changing teams, the map will not change direction. Users can modify the radar map image (if they want to add text positions to the image). I hope to improve it in the future. Thank you again, author！
![WVBR%O3J8~XR_9M)J _I`2U](https://github.com/user-attachments/assets/2b2d43dc-0925-486f-9872-08e8a65fdbdc)

**Comment by Enoouo** [comment]
Can't you see the settings button in the top left corner? You can set the centering and view rotation options there.

Additionally, since you understand Chinese, why not communicate in Chinese?

**Comment by kisadfnlnv** [comment]
上面那个人不是我··· 他在我这条评论的，我以为作者你用英语来着，会中文就好沟通了，我远程telnet测试端口是可以访问的，就还是远程域名加载不出雷达画面，局域网是没有问题的

**Comment by 857868581** [comment]
电脑端访问一切正常，手机端访问就是这个样子，手机端用了Safari和edge浏览器测试，下面多出一片空白
![514585DE80421F8922E09366C131AA4B](https://github.com/user-attachments/assets/89565add-344f-46dc-9eff-5a46629797f7)

**Comment by kisadfnlnv** [comment]
> 电脑端访问一切正常，手机端访问就是这个样子，手机端用了Safari和edge浏览器测试，下面多出一片空白 ![514585DE80421F8922E09366C131AA4B](https://private-user-images.githubusercontent.com/114120906/373939031-89565add-344f-46dc-9eff-5a46629797f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMTA1NDYsIm5iZiI6MTcyODIxMDI0NiwicGF0aCI6Ii8xMTQxMjA5MDYvMzczOTM5MDMxLTg5NTY1YWRkLTM0NGYtNDZkYy05ZWZmLTVhNDY2Mjk3OTdmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQxMDI0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTJiYjk4YWJjY2ExZjdjY2QxOGI4ODZkYzI0ODYyZjZiYWI3NmFlNmFkYTJmM2JkOGRiMzgwZDgwY2E0NDY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4PhfJh8lA9WUSIQN9zeb7a-XMjLjiTrx99n96ENxl0c)

大哥你能不能新起一个问题，这样 作者都搞混掉谁是谁了

**Comment by kisadfnlnv** [comment]
> 加密平台?5e?

是的  5E平台

**Comment by Enoouo** [comment]
哈哈哈，确实给我整晕了，你们有discord吗？我可以帮你看一下

**Comment by kisadfnlnv** [comment]
> 哈哈哈，确实给我整晕了，你们有discord吗？我可以帮你看一下

是VPN嘛  discord？  其他todesk  向日葵方便吗

**Comment by Enoouo** [comment]
discord 是个聊天工具，没有算了，留QQ吧，我加一下，了解一下具体情况
todesk 可以

**Comment by kisadfnlnv** [comment]
> discord 是个聊天工具，没有算了，留QQ吧，我加一下，了解一下具体情况 todesk 可以

QQ:423858029

**Comment by 857868581** [comment]
discord
857868581_90769

**Comment by 857868581** [comment]
我在discord里给你发送了一条“有问题可以在这里反馈吗”的信息之后，账号就被禁用了，为什么呢
![image](https://github.com/user-attachments/assets/1d398db8-c83b-43cd-aee7-e33082ea7205)

**Comment by Enoouo** [comment]
哈哈哈，可能跟你的梯子有关，你留QQ吧

**Comment by 857868581** [comment]
857868581
