### ISSUE TITLE
反后坐力有问题

### ISSUE THREAD

**Issue by timelock66** [Enoouo/Pro-CS2_DMA#44]
开启了反后坐力但是没有效果，Kmbox b pro 自瞄是有效果的 
topmost=1
layered=1
transparent=2
layeredAlpha=0 调成0 背景还是黑色 用moonlight串流还是覆盖不了当前画面

**Comment by Enoouo** [comment]
后坐力补偿没有问题，只有自瞄生效的时候后坐力补偿才会生效
layeredAlpha 现在好像不能完全透明，不要设置成0

**Comment by timelock66** [comment]
好的 我去试试看
