### ISSUE TITLE
Current offsets

### ISSUE THREAD

**Issue by Yoss101** [Enoouo/Pro-CS2_DMA#46]
Put this in the main directory of pro cs2 on second pc
[offsets.json](https://github.com/user-attachments/files/17302647/offsets.json)

**Comment by CKJ7921** [comment]
这个只能透视自瞄无效

**Comment by CKJ7921** [comment]
Failed to initialize keyboard hotkeys through kernel.

**Comment by CKJ7921** [comment]
突然又能用了，哈哈
