### ISSUE TITLE
Aimbot not working with my KMBOX Net

### ISSUE THREAD

**Issue by Geitost** [Enoouo/Pro-CS2_DMA#47]
I am using standard config but have of course changed the KMBOX IP, port and UUID but the aimbot does still not work. Do I need to alter anything else, the console says Failed to initialize keyboard hotkeys through kernel which is the only thing I see that may be the problem. 

Thank you for the help, everything else is working perfectly!

**Comment by kisskefou** [comment]
change Windows version win11 21h2

**Comment by Enoouo** [comment]
What is your system version number?

**Comment by Kprobem** [comment]
我是用Win11 24H2同样无法使用,副机也是使用Win11 LTSC 24H2

**Comment by yakobie** [comment]
Will this work on windows 10? When I hold trigger key it just shoots regardless of where I am aimed. It also shoots magnet trigger without moving. Aimbot also does not move
