### ISSUE TITLE
Magnet Trigger is broken?

### ISSUE THREAD

**Issue by ogdar0** [Enoouo/Pro-CS2_DMA#48]
Everytime I hold magnet trigger key it just randomly shoots, even if there is no enemy

**Comment by Yoss101** [comment]
This isn't entirely true. Magnet trigger fires when you press the key regardless of if there is an enemy in the fov. The normal trigger will fire any time when you release the button. This should not be worked on currently in my opinion. I would love to be able to update this myself when the source is released.

**Comment by Enoouo** [comment]
This is intentional. Regardless of whether there is a target, the system will shoot after a certain delay. It's designed this way to appear more natural.
