### ISSUE TITLE
ESP Config

### ISSUE THREAD

**Issue by turtlechipschocolate** [Enoouo/Pro-CS2_DMA#49]
I am running the software on my laptop which is also connected to my main computer via fuser. I see there is an ESP option which I tried to config with results not changing much. Does this software support fuser? I am trying to get the ESP overlay onto my main computer.

**Comment by turtlechipschocolate** [comment]
To add context, when I run CS2 software, it opens a render image for ESP. How do I transfer that into my main desktop? I tried it with a different computer and same issue (Secondary PC).

Also, is there a way to make the radar more smooth. It feels like it loses data / packets and doesn't update for a while. Maybe I am missing something but I am using it directly from releases with no further applications installed.

**Comment by ogdar0** [comment]
whats your DMA speedtest?

**Comment by turtlechipschocolate** [comment]
Would that be an issue? I see the ESP they are just on my second monitor. I would like to move it to my main pc monitor.

**Comment by ogdar0** [comment]
> Would that be an issue? I see the ESP they are just on my second monitor. I would like to move it to my main pc monitor.

Make sure your fuser is installed properly
https://github.com/sebhansen/Fuser-Guide

**Comment by turtlechipschocolate** [comment]
fuser is installed properly. i know because i use a different software for rust and it uses fuser.

the issue is i do not see the top window bars to drag the ESP over. Where should I be grabbing or what should my config be? @ogdar0

**Comment by ogdar0** [comment]
For me its working properly, but you can try change this in config.cfg
Also make sure, the resolution is set properly in config.cfg, if its still not working then try to play cs2 in fullscreen windowed mode.

layered=0 change to 1
transparent=0 change to 1

**Comment by HH333** [comment]
Everything seems to be working fine

**Comment by turtlechipschocolate** [comment]
@HH333 can I get your configs as well ?

**Comment by Enoouo** [comment]
Has your issue been resolved?
