### ISSUE TITLE
pls update it1

### ISSUE THREAD

**Issue by xndhn** [Enoouo/Pro-CS2_DMA#50]
1

**Comment by HH333** [comment]
Everything is OK

**Comment by CKJ7921** [comment]
我这也不能用了

**Comment by timelock66** [comment]
You Can update offset.json

**Comment by CKJ7921** [comment]
发一下啊

**Comment by timelock66** [comment]
> 发一下啊

作者的fork里面不是有吗 直接复制丢进去就完了啊

**Comment by CKJ7921** [comment]
我咋找不到，大佬能截个图吗

**Comment by CKJ7921** [comment]
作者好久没更新了吧，CS2更新好几次了

**Comment by timelock66** [comment]
https://github.com/a2x/cs2-dumper 这个里面也有

**Comment by CKJ7921** [comment]
谢谢大佬

**Comment by God626** [comment]
今天的偏移是不是有问题？替换了没用

**Comment by timelock66** [comment]
游戏今天更新了 自己抓一下偏移就好了

**Comment by CKJ7921** [comment]
怎么抓有教程吗，推荐一下学学

**Comment by timelock66** [comment]
https://github.com/a2x/cs2-dumper  这项目里不是写了吗

**Comment by CKJ7921** [comment]
好的我看看

**Comment by CKJ7921** [comment]
换了最新的偏移量，透视有，自瞄范围也显示，但是自瞄效果没了。参数还是原来能用的时候的参数

**Comment by God626** [comment]
> 游戏今天更新了 自己抓一下偏移就好了

请问有遇到雷达重叠的问题吗？我的网页雷达打开之后，人物头像全部重叠在一块，也不移动
![Uploading 56B03949C0D4C900349F6CC2E3468966.jpg…]()
[](url)

**Comment by timelock66** [comment]
#55 没遇到过

**Comment by Enoouo** [comment]
稍后添加自动更新，在此之前先手动更新吧
