### ISSUE TITLE
DMA 无法正常运行 求解决办法

### ISSUE THREAD

**Issue by cs2-cheat** [Enoouo/Pro-CS2_DMA#54]
![image](https://github.com/user-attachments/assets/24a08de2-cddc-4e1a-af18-6394d2fc024f)
不知道为什么无法运行，我是否可以通过关闭程序来达到运行目的？或者是笔记本无法使用？作者能否出一个详细教程，下载的三个文件到底是要全部都下还是只需要下载一个？解压缩后还需要做什么，我的格式是正确的，却不知道为什么无法解决，求作者回复，谢谢。
![image](https://github.com/user-attachments/assets/30d1545a-c8e4-4346-99c3-6370ecf673b0)
![image](https://github.com/user-attachments/assets/d69d5340-913c-4a47-b4e8-46ffbbc81f53)
![image](https://github.com/user-attachments/assets/b4a18644-7bd0-44f2-9ab9-c4aa1e4092eb)
(I don't know why it can't run, can I do it by closing the program? Or is the laptop not working? Can the author come up with a detailed tutorial on whether to download all three files or only one file? What else do I need to do after unzipping, my format is correct, but I don't know why it can't be solved, I beg the author to reply, thank you.)

**Comment by timelock66** [comment]
你先测速看看你的板子有没有问题 板子都链接不上

**Comment by Enoouo** [comment]
像上面说的，检查你DMA是否已连接，或说是你是否拥有DMA卡

**Comment by cs2-cheat** [comment]
> 像上面说的，检查你DMA是否已连接，或说是你是否拥有DMA卡

笔记本有DMA吗，怎么检查是否连接啊？

**Comment by cs2-cheat** [comment]
> 你先测速看看你的板子有没有问题 板子都链接不上

怎么测速。。。纯新手，啥也不会，不知道有没有这个功能

**Comment by Enoouo** [comment]
> > 像上面说的，检查你DMA是否已连接，或说是你是否拥有DMA卡
> 
> 笔记本有DMA吗，怎么检查是否连接啊？

DMA是一个硬件，看来你没有
