### ISSUE TITLE
有人遇到雷达重叠的问题吗

### ISSUE THREAD

**Issue by God626** [Enoouo/Pro-CS2_DMA#55]
如题，方框和骨骼正常，但是雷达都是重叠在一块的，怎么解决
![Uploading 56B03949C0D4C900349F6CC2E3468966.jpg…]()
![Uploading 56B03949C0D4C900349F6CC2E3468966.jpg…]()

**Comment by Kprobem** [comment]
update all json

**Comment by God626** [comment]
> 更新所有 json

如何更新呢？

**Comment by God626** [comment]
![56B03949C0D4C900349F6CC2E3468966](https://github.com/user-attachments/assets/6ac4c237-46d8-4400-84c4-4f8ae6251a2d)
![Uploading 56B03949C0D4C900349F6CC2E3468966.jpg…]()

**Comment by Enoouo** [comment]
[client.dll.json](https://github.com/user-attachments/files/17489924/client.dll.json)
[offsets.json](https://github.com/user-attachments/files/17489927/offsets.json)
用最新的偏移量也这样吗？

**Comment by LannYuu** [comment]
> [client.dll.json ](https://github.com/user-attachments/files/17489924/client.dll.json) [offsets.json](https://github.com/user-attachments/files/17489927/offsets.json) 用最新的偏移量也这样吗？

我更新了偏移量，人物透视是正常了，雷达还是这样 叠在一起

**Comment by Enoouo** [comment]
> > [client.dll.json ](https://github.com/user-attachments/files/17489924/client.dll.json) [offsets.json](https://github.com/user-attachments/files/17489927/offsets.json) 用最新的偏移量也这样吗？
> 
> 我更新了偏移量，人物透视是正常了，雷达还是这样 叠在一起

尝试下载新版本
