### ISSUE TITLE
人物显示不全

### ISSUE THREAD

**Issue by Kprobem** [Enoouo/Pro-CS2_DMA#56]
娱乐模式敌对方人物会显示不全，部分时候只剩下1-2个玩家正常绘制，其他模式正常。
Aimbot失效，使用KmboxNet显示初始化正常

**Comment by Enoouo** [comment]
玩家列表有上限，超出不显示，下个版本会自定义最大玩家数。
KmboxNet初始化成功，Aimbot失效的话，先检查偏移文件是否是最新的？
另外是否出现了 [!] Failed to initialize keyboard hotkeys through kernel.

**Comment by Kprobem** [comment]
Aimbot关闭Check后能用了.....
