### ISSUE TITLE
默认关闭UI

### ISSUE THREAD

**Issue by 1270641972** [Enoouo/Pro-CS2_DMA#60]
能否在CFG内添加一个关闭UI的
现在打开软件默认弹出UI，玩雷达是用不到的
不知是什么原因我的扳机没有效果，绑定按键都正常在训练场正常实战没有效果

感谢大佬分享项目！

**Comment by Enoouo** [comment]
disable_render_layer=1 是禁用渲染层
训练场正常实战没效果？扳机还是自瞄还是磁性扳机？

**Comment by 1270641972** [comment]
> disable_render_layer=1 是禁用渲染层 训练场正常实战没效果？扳机还是自瞄还是较差扳机？

你好大佬，扳机和磁性都没有效果。自瞄是有效果的，有时候游戏刚刚开始时有效果的然后就没有了。
如方便的话，能否加一个默认不打卡UI的 CFG设置，磁轴键盘 没有INS键位 哈哈哈

**Comment by Enoouo** [comment]
disable_render_layer=1 的时候就不会有任何UI
"有时候游戏刚刚开始时有效果的然后就没有了。"  是全没了吗？包括自瞄、扳机、磁性扳机？
你用的kmbox吗？哪个型号？玩的什么平台？

**Comment by 1270641972** [comment]
KMBOX net ，我在官匹休闲人机模式测试时有时候刚进去是有效果的但是打一两句就没有了，自瞄是一直有效果。只是扳机不行
平台也是一样的。我的意思是能否单独加一个控制UI自动打开的CFG参数，并不是一个非常必要的哈哈哈，只是喜欢 以前版本的样子不会弹出来

**Comment by 1270641972** [comment]
感谢大佬的贡献！

**Comment by Enoouo** [comment]
disable_render_layer=1 的时候就不会有任何UI，这句话你选择性看不到吗？
至于扳机失效的问题，可能是你设置的问题？或者其他问题，目前没有人反馈这个问题，我也没遇到，使用默认参数试试是否正常，另外休闲玩家数量比较多，或许需要设置 max_players=64

**Comment by Enoouo** [comment]
![image](https://github.com/user-attachments/assets/2b514158-825c-4565-8c61-4f264a0e2d2f)
另外菜单上也有相关选项设置

**Comment by 1270641972** [comment]
![Uploading 2.png…]()
请问大佬这个报错是什么原因导致的，是因为我的cfg吗

**Comment by 1270641972** [comment]
![2](https://github.com/user-attachments/assets/5ddba7f4-7aa4-42ca-80ad-02f7bc4f036a)

**Comment by Enoouo** [comment]
系统版本太低了

**Comment by 1270641972** [comment]
主机和副机都是WIN10 副机是22H2不应该呀，刚开始是好用的

**Comment by Enoouo** [comment]
那就尝试重启游戏机

**Comment by 1270641972** [comment]
尝试过了，会不会是缓存导致的，方便加您个QQ或者V嘛

**Comment by Enoouo** [comment]
> 尝试过了，会不会是缓存导致的，方便加您个QQ或者V嘛

还在？我改了下代码，你能测试么？

**Comment by 1270641972** [comment]
> > 尝试过了，不会是存储导致的，方便加您个QQ或者V嘛
> 
> 还在吗？我修改了下代码，你能测试么？

可以测试，我可以添加你的discord

**Comment by 1270641972** [comment]
或者您可以添加我：dqy0730#2100
