### ISSUE TITLE
keyboard hotkeys

### ISSUE THREAD

**Issue by gyulka** [Enoouo/Pro-CS2_DMA#64]
https://imgur.com/a/mAi4yIm
[!] Failed to initialize keyboard hotkeys through kernel, This will cause the aimbot to malfunction. Please specify your system version in the Issues.
aim, trigger doesn't work. using kmbox net

**Comment by Enoouo** [comment]
I can try modifying the code, but I don't have a Windows 10 system to test it on. Perhaps you could help me test it? If you're willing, you can leave your Discord.

**Comment by Enoouo** [comment]
> update KB5045594

will updating KB5045594 solve the issue?

**Comment by Enoouo** [comment]
[Pro CS2.zip](https://github.com/user-attachments/files/17547226/Pro.CS2.zip)
Have you already uninstalled KB5045594? If not, try this

**Comment by Enoouo** [comment]
[Pro CS2-2.zip](https://github.com/user-attachments/files/17547988/Pro.CS2-2.zip)
try this

**Comment by Enoouo** [comment]
were the other features working properly in the previous version?

**Comment by Enoouo** [comment]
I remember adding you on Discord, right?

**Comment by Enoouo** [comment]
check your discord

**Comment by Enoouo** [comment]
[Pro CS2-3.zip](https://github.com/user-attachments/files/17548874/Pro.CS2-3.zip)
If it still doesn't work, let's fix it tomorrow. Also, try it in bot matches.

**Comment by gyulka** [comment]
> I can try modifying the code, but I don't have a Windows 10 system to test it on. Perhaps you could help me test it? If you're willing, you can leave your Discord.

__gyulka__ here's my discord
also tried both new version, well it doesn't work for me too

**Comment by gyulka** [comment]
also 26 minutes ago cs2 got an update and your cheats just crashing

**Comment by God626** [comment]
作者你好，游戏今天更新，并没有实现自动更新偏移，提示： Failed to Execute Scatter Read，自助获取偏移替换后，打开软件会提示软件停止运行

**Comment by 1270641972** [comment]
其实并不需要自动更新偏移，手动下载也是一样的。那样已经运行了很久

**Comment by God626** [comment]
> 其实并不需要自动更新偏移，手动下载也一样。已经运行很久了

今天游戏更新，我自己替代了偏移，但是一运行软件，获取完地图，就显示停止工作了，您今天有这个情况存在吗？

**Comment by Enoouo** [comment]
> 作者你好，游戏今天更新，并没有实现自动更新偏移，提示： Failed to Execute Scatter Read，自助获取偏移替换后，打开软件会提示软件停止运行

没自动更新是因为更新源2小时前才更新

**Comment by Enoouo** [comment]
> 其实并不需要自动更新偏移，手动下载也是一样的。那样已经运行了很久

不是所有人都会手动更新

**Comment by Enoouo** [comment]
> also 26 minutes ago cs2 got an update and your cheats just crashing

crash? is there any prompt?

**Comment by gyulka** [comment]
> > also 26 minutes ago cs2 got an update and your cheats just crashing
> 
> crash? any tips?

it's trying to start but after cli text `[-] Initializing memory manager, please have patience if it takes a while...
[+] Initializing KMbox...
[!] Failed to initialize KMbox NET
[+] Counter-Strike 2 found.
[^] System version: 19045
found gafAsyncKeyState at: 0xFFFFB8A3892518C0
[!] Failed to initialize keyboard hotkeys through kernel, This will cause the aimbot to malfunction. Please specify your system version in the Issues.` exe file just go exit

**Comment by gyulka** [comment]
[offsets.zip](https://github.com/user-attachments/files/17553887/offsets.zip)
my offsets
