### ISSUE TITLE
1.33版本辅助瞄准都失效了

### ISSUE THREAD

**Issue by nestacui** [Enoouo/Pro-CS2_DMA#66]
topmost=1
layered=0
transparent=0
layeredAlpha=255
targetFPS=240
showFPS=1
vsync=1
disable_render_layer=0
aimbot_active=1
aimbot_fov=6.710000
aimbot_dynamic_fov=0.000000
aimbot_fovCircle=0
aimbot_smooth=2.276000
aimbot_rcs_active=1
aimbot_key=0
aimbot_isAimbotKey=1
aimbot_custom_key=0
aimbot_check=1
aimbot_teamCheck=1
aimbot_pistol_active=1
aimbot_smg_active=1
aimbot_sniper_active=0
aimbot_rifle_active=1
aimbot_shotgun_active=1
aimbot_machineGun_active=0
aimbot_pistol_bones=6
aimbot_smg_bones=6,5
aimbot_shotgun_bones=6,5
aimbot_rifle_bones=6,5
aimbot_sniper_bones=6,5,4,2
aimbot_machinegun_bones=6,5

**Comment by Enoouo** [comment]
检查自己的偏移数据
