### ISSUE TITLE
No effect

### ISSUE THREAD

**Issue by ccbo1** [Enoouo/Pro-CS2_DMA#68]
I injected it, but it didn't work. How can I solve it?And it has no effect.

**Comment by Enoouo** [comment]
show your console log

**Comment by ccbo1** [comment]
> show your console log

![wx_camera_1730367903791.jpg](https://github.com/user-attachments/assets/e8b9bf1c-657a-4d14-99a3-749703df3169)

**Comment by Enoouo** [comment]
偏移数据过时了，你的网络不足以让程序访问GitHub，无法更新偏移数据，要么解决网络问题，要么手动更新偏移文件。
https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/client_dll.json > client.dll.json
https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/offsets.json > offsets.json
