### ISSUE TITLE
程序闪退

### ISSUE THREAD

**Issue by sayori-cg** [Enoouo/Pro-CS2_DMA#69]
![1730463935128](https://github.com/user-attachments/assets/e93b895f-6d40-4ad0-a858-cd07c47f6bf4)
出现这个然后闪退
[client.dll.json](https://github.com/user-attachments/files/17599601/client.dll.json)
[offsets.json](https://github.com/user-attachments/files/17599603/offsets.json)

**Comment by sayori-cg** [comment]
@Enoouo

**Comment by Enoouo** [comment]
看报错是哪个json文件格式不对吧？你重新检查一下

**Comment by sayori-cg** [comment]
![image](https://github.com/user-attachments/assets/b04ca842-b337-49f9-9edf-4fea05e99789)
我看项目里面只有这俩json，我把map和radar文件夹删除之后的整个包上传了，client和offsets都是复制的上一个issues你发的地址，没找到啥问题
[Pro CS2.zip](https://github.com/user-attachments/files/17606974/Pro.CS2.zip)
@Enoouo

**Comment by ShukebtAb** [comment]
根据我的尝试，可能和副机网络有关

**Comment by sayori-cg** [comment]
是的，我的辅机连不上更新服务器，所以我是手动更新的偏移和数据json

**Comment by ShukebtAb** [comment]
根据我的尝试，你可以先禁止网络，开启软件，等待加载完成以后再打开网络。这会让你加载进去，正常游戏。但是我不知道这会不会导致一些功能失效

**Comment by ShukebtAb** [comment]
当更新报错的时候，程序会在你的根目录下生成一个0kb的offset文件

**Comment by Enoouo** [comment]
应该就是这个问题吧，下个版本我处理一下网络异常的问题
