### ISSUE TITLE
Web Radar

### ISSUE THREAD

**Issue by PyCryption** [Enoouo/Pro-CS2_DMA#70]
![image](https://github.com/user-attachments/assets/a98b3c98-2aed-4a8c-b7d9-dc88b5949333)
I have a problem when I launch the radar, I get knocked out that the radar is connected, or just an empty page without a map, I have already tried both 7788 and 3344, I do not understand what the problem is, I managed to do something once, but instead of any information there was (Update required)

**Comment by PyCryption** [comment]
I made some progress in this, I was able to launch the radar, but I don't understand how to distribute it to a friend, I downloaded Radmin VPN, how should a friend connect?

**Comment by Enoouo** [comment]
https://github.com/Enoouo/Pro-CS2_DMA/issues/36

**Comment by PyCryption** [comment]
Did I understand correctly that I need to specify the IP Radmin VPN in the IP web radar? And then the person who is connected to my network will be able to log in over the local network?

**Comment by Enoouo** [comment]
Keep 127.0.0.1 unchanged, and have your friend access your Radmin VPN IP address. For example, if your Radmin VPN IP address is 123.12.13.145, your friend can connect successfully and access 123.12.13.145:3344.

**Comment by PyCryption** [comment]
![image](https://github.com/user-attachments/assets/4111bf7e-d087-4b58-8b63-01c7d4ff555c)
![image](https://github.com/user-attachments/assets/adb2a613-e523-46cf-8eae-ff776af1ac7c)
![image](https://github.com/user-attachments/assets/3a23d101-80d0-4bfc-b7e1-d15121492097)

**Comment by Enoouo** [comment]
DMA PC, turn off the firewall or open the port.

**Comment by PyCryption** [comment]
I've done everything now with IP radmin:3344 issues Upgrade Required
![image](https://github.com/user-attachments/assets/427cb4c6-7abd-4ffd-b819-fe5c4eb6ac67)

**Comment by Enoouo** [comment]
try close the firewall

**Comment by PyCryption** [comment]
off | upgrade required

**Comment by Enoouo** [comment]
net name:
password:
I'll try

**Comment by PyCryption** [comment]
name kantik221 pass kantik221

**Comment by Enoouo** [comment]
sry, port: 7788
![image](https://github.com/user-attachments/assets/6e686c7a-f3c7-46f1-8357-3944f01ea212)

**Comment by PyCryption** [comment]
bruh :D
thx bro i love you

**Comment by Enoouo** [comment]
⭐ the project, the radar will be updated with some new content soon.
