### ISSUE TITLE
error with kmbox

### ISSUE THREAD

**Issue by Redbullfeen** [Enoouo/Pro-CS2_DMA#78]
![image_2024-11-16_141618914](https://github.com/user-attachments/assets/f4de5f4e-560f-4d22-ac54-725fe70d3c70)

**Comment by 13Gizmo12** [comment]
you have a dma card?

**Comment by Redbullfeen** [comment]
I don't know

**Comment by Redbullfeen** [comment]
I'm guessing not

**Comment by 13Gizmo12** [comment]
-.-!!
