### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by DarkAssist** [Enoouo/Pro-CS2_DMA#8]
![image](https://github.com/user-attachments/assets/a5660fb3-a24d-4acc-923c-57445b9078cd)
disable rendering layer

**Comment by DarkAssist** [comment]
The ESP render does not appear. It does not respond to 0 and 1

**Comment by Enoouo** [comment]
I noticed this issue, and it seems to be related to having Chinese comments in the code. Try removing the comments or deleting the config file. When you run the program again, it will automatically create a new config file.

If this is the reason, please let me know.

**Comment by Fvr9W** [comment]
并不会自动生成配置文件

**Comment by Fvr9W** [comment]
我把所有注释都删了还是提示 disable rendering layer

**Comment by Enoouo** [comment]
> 并不会自动生成配置文件

Sry, 确实不会自动生成，后面我发现相关代码被我注释掉了

> 我把所有注释都删了还是提示 disable rendering layer

昨天有人遇到后删除注释正常工作，不行吗？稍后我测试一下

**Comment by DarkAssist** [comment]
deleting the esp_active 1 line helped

**Comment by Enoouo** [comment]
Fixed. Please download again.
