### ISSUE TITLE
程序卡在加载内存控制器

### ISSUE THREAD

**Issue by 1678190157** [Enoouo/Pro-CS2_DMA#83]
一直卡在那个地方，是需要联网吗

**Comment by Enoouo** [comment]
贴控制台截图或者复制控制台信息贴上来

**Comment by 1678190157** [comment]
![捕1获](https://github.com/user-attachments/assets/34135f8b-3822-4c7a-ae9d-7b1992a197d3)

**Comment by 1678190157** [comment]
![Uploading 捕获.PNG…]()

**Comment by 1678190157** [comment]
![捕获](https://github.com/user-attachments/assets/f72fbdea-0707-4940-a9ed-cd184b93e11d)
可以启动控制ui，但是游戏里没效果

**Comment by 1678190157** [comment]
██████╗ ██████╗  ██████╗       ██████╗███████╗   ████████═╗
  ██╔══██╗██╔══██╗██╔═══██╗     ██╔════╝██╔════╝   ╚════███╔╝
  ██████╔╝██████╔╝██║   ██║     ██║     ███████╗      ███╔═╝
  ██╔═══╝ ██╔══██╗██║   ██║     ██║     ╚════██║    ███ ╔╝
  ██║     ██║  ██║╚██████╔╝██╗  ╚██████╗███████║   ████████╗
  ╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚═╝   ╚═════╝╚══════╝   ╚═══════╝

  v1.33                                    [此软件为免费分享]
                                Github.com/Enoouo/Pro-CS2_DMA

[-] 正在初始化内存管理器，如果需要一些时间，请耐心等待...
[!] request error: Timeout was reached
[!] 网络异常或是访问Github失败，无法检查软件更新情况
[!] request error: Timeout was reached
[!] 网络异常或是访问Github失败，无法检查CS2版本
JSON parse error: [json.exception.parse_error.101] parse error at line 1, column 1: attempting to parse an empty input; check that your input string or stream contains the expected JSON
JSON parse error: [json.exception.parse_error.101] parse error at line 1, column 1: attempting to parse an empty input; check that your input string or stream contains the expected JSON
JSON parse error: [json.exception.parse_error.101] parse error at line 1, column 1: attempting to parse an empty input; check that your input string or stream contains the expected JSON
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
JSON parse error: [json.exception.parse_error.101] parse error at line 1, column 1: attempting to parse an empty input; check that your input string or stream contains the expected JSON
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[!] Error in get_arithmetic_value: type must be number, but is null
[+] Initializing KMbox...
[+] KMbox NET 初始化成功
[-] 等待 反恐精英2 启动中......

**Comment by Enoouo** [comment]
是因为你连接不到更新数据的地址，无法更新自然没效果，先手动替换这两个文件吧，有空我在国内做个更新源
[offsets.json](https://github.com/user-attachments/files/17979290/offsets.json)
[client.dll.json](https://github.com/user-attachments/files/17979292/client.dll.json)
