### ISSUE TITLE
网页雷达共享支持

### ISSUE THREAD

**Issue by wjwrh** [Enoouo/Pro-CS2_DMA#85]
目前雷达在7788端口部署web服务器提供前端访问，我用frp将frp转发到公网端口上，但是通过公网端口访问发现页面全白。
我发现雷达的渲染是在前端进行的，通过ws://127.0.0.1:3344与Pro_CS2.exe进行通信，为了能实现共享网页雷达，我希望能实现下者之一：
1. 将渲染工作在服务端完成(工作量可能较大，我不太懂web开发)
2. 提供修改web socket地址配置的方式，这样我可以将ws端口一并转发出去，供远程主机使用

**Comment by Enoouo** [comment]
7788是web服务，你还需要开放3344端口用于数据传输

**Comment by Enoouo** [comment]
如果你不想用3344端口，数据传输的端口在雷达文件里的config中可以修改
